#!/usr/bin/env python3
"""Merge per-target backbone shards into the one collection the arms share.

    python scripts/merge_binder_backbones.py \
        --shards runs/binder_bench/shards --out runs/binder_bench/backbones

`cache_binder_backbones.py` writes one `backbones.json` per invocation, and
the ten AlphaProteo targets are independent, so they run as ten array tasks
rather than one eight-hour serial loop. That leaves ten manifests where the
design stage expects one.

The merge is not a concatenation. Phase 1A's arms are paired *because* they
consume an identical backbone collection, so a collection assembled from
shards that disagree about `n_step`, `eta`, `sigma_b`, `dtype`, `use_msa` or
the checkpoint hash is not one collection -- it is two experiments sharing a
directory. Every setting except the ones that are per-shard by construction
(`lengths`, `n_samples` may be narrowed for a rerun; `checkpoint_dir` is a
path) is therefore required to agree, and a disagreement is an error rather
than a note in the output.

Designs are hard-linked rather than copied: same filesystem, ~1 MB each, and a
link cannot silently diverge from the shard it came from.
"""
from __future__ import annotations

import argparse
import json
import os
from pathlib import Path
from typing import Any

# Settings that define the shared collection. `lengths`/`n_samples` are
# deliberately absent: a target re-run to fill in one length is still part of
# the same collection.
MUST_AGREE = (
    "n_step", "eta", "sigma_b", "dtype", "use_msa", "seed", "fixed_target",
)


def main() -> None:
    parser = argparse.ArgumentParser(
        description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter
    )
    parser.add_argument("--shards", required=True,
                        help="directory of per-target cache_binder_backbones outputs")
    parser.add_argument("--out", required=True)
    parser.add_argument("--expect-targets", type=int, default=None,
                        help="fail unless exactly this many shards are present")
    parser.add_argument("--expect-designs", type=int, default=None,
                        help="fail unless exactly this many designs are merged")
    args = parser.parse_args()

    shards = sorted(
        p for p in Path(args.shards).expanduser().resolve().iterdir()
        if (p / "backbones.json").is_file()
    )
    if not shards:
        raise SystemExit(f"no shard carries a backbones.json under {args.shards}")

    out = Path(args.out).expanduser().resolve()
    (out / "designs").mkdir(parents=True, exist_ok=True)

    merged: dict[str, Any] = {}
    designs: list[dict[str, Any]] = []
    seen: dict[str, str] = {}
    per_target: dict[str, int] = {}

    for shard in shards:
        manifest = json.loads((shard / "backbones.json").read_text())
        settings = manifest["settings"]
        if not merged:
            merged = {
                "settings": dict(settings),
                "sources": manifest["sources"],
                "shards": [],
            }
            merged["settings"]["lengths"] = sorted(settings["lengths"])
        else:
            for key in MUST_AGREE:
                if settings.get(key) != merged["settings"].get(key):
                    raise SystemExit(
                        f"{shard.name}: {key}={settings.get(key)!r} but the "
                        f"collection so far has {merged['settings'].get(key)!r}. "
                        "These shards are not one paired collection."
                    )
            if manifest["sources"] != merged["sources"]:
                raise SystemExit(
                    f"{shard.name} was generated by a different runtime than "
                    "the earlier shards; see `sources` in each backbones.json"
                )
            merged["settings"]["lengths"] = sorted(
                set(merged["settings"]["lengths"]) | set(settings["lengths"])
            )

        for record in manifest["designs"]:
            design_id = record["design_id"]
            if design_id in seen:
                raise SystemExit(
                    f"{design_id} appears in both {seen[design_id]} and "
                    f"{shard.name}"
                )
            seen[design_id] = shard.name
            source = Path(record["path"])
            if not source.is_file():
                raise SystemExit(f"{design_id}: {source} is missing")
            destination = out / "designs" / source.name
            if destination.exists():
                destination.unlink()
            try:
                os.link(source, destination)
            except OSError:
                destination.write_bytes(source.read_bytes())
            record = dict(record, path=str(destination), shard=shard.name)
            designs.append(record)
            per_target[record["target"]] = per_target.get(record["target"], 0) + 1
        merged["shards"].append(shard.name)

    merged["designs"] = sorted(designs, key=lambda d: d["design_id"])
    merged["settings"]["n_designs"] = len(designs)
    merged["settings"]["designs_per_target"] = per_target
    (out / "backbones.json").write_text(
        json.dumps(merged, indent=2, sort_keys=True, default=str) + "\n"
    )

    for target, count in sorted(per_target.items()):
        print(f"{target:<8} {count:>4} design(s)")
    rmsds = [d["event_to_final_rmsd"] for d in designs]
    print(f"\n{len(designs)} design(s) from {len(shards)} shard(s) -> {out}")
    print(f"event -> final backbone RMSD: min {min(rmsds):.2f} "
          f"median {sorted(rmsds)[len(rmsds) // 2]:.2f} max {max(rmsds):.2f} A")

    if args.expect_targets is not None and len(per_target) != args.expect_targets:
        raise SystemExit(
            f"{len(per_target)} target(s) merged, expected {args.expect_targets}"
        )
    if args.expect_designs is not None and len(designs) != args.expect_designs:
        raise SystemExit(
            f"{len(designs)} design(s) merged, expected {args.expect_designs}"
        )


if __name__ == "__main__":
    main()
